<a href="https://colab.research.google.com/github/andres-merino/Curso-FundMachineLearning/blob/main/3-Notebooks/09-5-Lectura-Modelos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<table style="border: none; border-collapse: collapse;">
    <tr>
        <td style="width: 20%; vertical-align: middle; padding-right: 10px;">
            <img src="https://i0.wp.com/see-ec.org/wordpress/wp-content/uploads/2023/01/LOGO-SEE-texto-blanco-3.png?w=1356&ssl=1" width="200">
        </td>
        <td style="width: 2px; text-align: center;">
            <font color="#008dc3" size="7">|</font><br>
            <font color="#008dc3" size="7">|</font>
        </td>
        <td>
            <p style="font-variant: small-caps;"><font color="#008dc3" size="5">
                <b>Sociedad Ecuatoriana de Estadística</b>
            </font> </p>
            <p style="font-variant: small-caps;"><font color="#008dc3" size="4">
                Fundamentos de Machine Learning &bull; Lectura de Modelos
            </font></p>
            <p style="font-style: oblique;"><font color="#008dc3" size="3">
                Andrés Merino &bull; Febrero 2026
            </font></p>
        </td>  
    </tr>
</table>

---
## <font color='008dc3'> Introducción </font>

Este notebook está diseñado como una guía introductoria para implementar la lectura de modelos de aprendizaje automático en Python.

Los paquetes necesarios son:

In [1]:
import pandas as pd  # Manejo de datos

import joblib
import pickle

### <font color='008dc3'> Lectura de datos  </font>

Generamos nuevos datos para usar el modelo.

In [2]:
# Tomo las columnas de interés
numeric_cols = ['Attack', 'Defense', 'Speed', 'Sp. Atk', 'Sp. Def', 'HP']

# Genero un DataFrame con los datos
data = pd.DataFrame({'Name': ['P1', 'P2', 'P3'],
    'Attack': [49, 62, 100],
    'Defense': [49, 63, 100],
    'Speed': [45, 60, 100],
    'Sp. Atk': [49, 50, 100],
    'Sp. Def': [65, 50, 100],
    'HP': [45, 60, 100]})

# Muestro los primeros registros
display(data.head())

  Name  Attack  Defense  Speed  Sp. Atk  Sp. Def   HP
0   P1      49       49     45       49       65   45
1   P2      62       63     60       50       50   60
2   P3     100      100    100      100      100  100

Leemos el modelo guardado en un archivo con pickle. Puedes descargar el modelo [aquí](https://raw.githubusercontent.com/andres-merino/Curso-FundMachineLearning/refs/heads/main/3-Notebooks/modelo_pokemon.pkl).

In [3]:
with open('modelo_pokemon.pkl', 'rb') as file:
    modelo = pickle.load(file)

Realizamos predicciones:

In [4]:
# Predicción
prediccion = modelo.predict(data[numeric_cols])

data['Stage_pred'] = prediccion

display(data)

  Name  Attack  Defense  Speed  Sp. Atk  Sp. Def   HP  Stage_pred
0   P1      49       49     45       49       65   45           2
1   P2      62       63     60       50       50   60           1
2   P3     100      100    100      100      100  100           0

Leemos el modelo guardado en un archivo con joblib. Puedes descargar el modelo [aquí](https://raw.githubusercontent.com/andres-merino/Curso-FundMachineLearning/refs/heads/main/3-Notebooks/modelo_pokemon.joblib).

In [5]:
with open('modelo_pokemon.joblib', 'rb') as file:
    modelo = joblib.load(file)

Realizamos predicciones:

In [6]:
# Predicción
prediccion = modelo.predict(data[numeric_cols])

data['Stage_pred'] = prediccion

display(data)

  Name  Attack  Defense  Speed  Sp. Atk  Sp. Def   HP  Stage_pred
0   P1      49       49     45       49       65   45           2
1   P2      62       63     60       50       50   60           1
2   P3     100      100    100      100      100  100           0